### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by MCinSeattle** [microsoft/audio-recorder#1]
1)  Open Recorder
2)  Tap on Quality to change to Stereo
3)  Press the Record button and record some audio.
4)  Tap on the File button to access the file you recorded.
5)  Play the file.
6)  Click Back to return to Recorder.
7)  Click Record.

  Application crashes - System.AccessViolationException in AudioRecorder.DLL ...
Attempted to read or write protected memory. ...

**Comment by kamenlitchev** [comment]
Same here (I copied ticket from https://projects.developer.nokia.com/wpaudiorecorder/ticket/2):

The WASAPI code can easily lead to heap corruption. This occurs when the UI thread is blocked (for example, a MessageBox is shown).

To reproduce:

1.Add the following code as last line of start record block in OnRecButtonTap? 

```
private void OnRecButtonTap?(object sender, System.Windows.Input.GestureEventArgs? e)
{
        ...
        RecLight.Source = lightImage;
        MessageBox.Show("Recording"); THIS CODE HERE
   }
}
```

2.Switch to WASAPI recording (stereo, 44K Hz) 
3.Start recording 
4.After few seconds, the app crashes with Heap corruption 

The crash happens in ReadBytes from the Dispatcher timer. Wait 4-5 seconds and close the MessageBox. App will quit crash.

I will debug later today to see where this happens, but a quick code inspection (with the help of a C person) shows that there is a chance for the memcopy to overflow when writing in GetBytes :)

**Comment by kamenlitchev** [comment]
Actually, there two possible cuases for the crash:
1. The forementioned buffer overflow
2. Memory relocation after GC. Consider the following code:

```
    byte[] audioBytes = null;
    int bytesRead = wasapi.ReadBytes(out audioBytes);
```

What is the chance that audioBytes gets relocated, but the native code still points to the old location? Thus, access violation is guaranteed to occur. Shouldn't there be some sort of pinning for audioBytes?

**Comment by tompaana** [comment]
Thanks a lot for reporting the issue and for the info and analysis! We'll look into this as soon as we can.

**Comment by kamenlitchev** [comment]
I confirm the buffer overflow. Any pause in the thread causes too much data to accumulate in mic buffer. Thus when the timer ticks, `ReadBytes` tries to consume all without array boundary check and goes beyond the maximum 1024_128 bytes in ``_tempBuffer`. After`accumulatedBytes`` reaches approximately 140 000, the app crashes :) Hope to have been of help! And thanks for the great sample!

BTW, if while recording the Back button is pressed so that Windows shows the app switching mode, after returning to the app, there's a good chance it will crash (since it has been paused and data has accumulated in the mic buffer).

**Comment by MCinSeattle** [comment]
Thank you kamenlitchev for sharing the overflow issue.  I also want to say thanks for the great sample app.  

I have not been able to make any progress on resolving the AccessViolationException but I have discovered that any Wasapi recording attempted after a Wasapi playback generates this error.
- -
  NOTE:  My past efforts have run into intermittent poor audio quality from XNA recordings, especially after the first one is stopped and another is started.  This led me to removing the buffer handler when an XNA Playback is stopped and adding it back when another Playback is started, something I believe should be done on the sample application but I haven't checked into it yet.

While the sample application doesn't support XNA playback of a stereo file I have found that I can record using Wasapi (trapping for the buffer overflow) and then playback using XNA (with a new instance of SoundEffect). 

I will anxiously await a solution to the AccessViolationException but it looks like I have a usable work-around that will meet my needs.  Thanks for the support!

**Comment by kamenlitchev** [comment]
@MCinSeattle I debugged and discovered that our issues are not connected. The problem that you have is caused by the Audio capture interface not properly being initialized on subsequent run after sound has been played. What happens is:
1. Audio render is started. This causes the internal state of WASAPI to be set to "running" and AudioManager to be "playing", too
2. Audio stops and AudioManager is no more "playing". However, WASAPI still is "running"
3. Capture is attempted. WASAPI, however, still thinks is "running" and does not initialize the Capture Device. Thus the first call to "ReadBytes" fails, because there is no Capture Device initialized.

You do not even need to record, then play, then record.

Workaround is to create new AudioManager or decouple the WASAPI object and recreate it every time.

**Comment by mikpiipp** [comment]
The original issue concerning an AccessViolationException after (Record ->) Play -> Record sequence fixed. The buffer overflow is also fixed with the same commit. Thank you for your vigilance and proposals.
